### ISSUE TITLE
Win/lose game

### ISSUE THREAD

**Issue by arumoy-shome** [shaw-rohit/SoftwareTesting2020#3]
As a user, I should be informed whether I won or lost a game. This information should be clear and indicated to me once the game ends. If I lose, then the game should prompt me to either start a new game or exit the game entirely. If I choose to exit the game then the game should end and I should be taken back to my terminal screen. If I choose to start a new game, then #1 should be invoked and the game should start from the beginning.

**Comment by Pungent-Paws** [comment]
Thinking of assigning myself to this one because it seems fun, but wondering if ideally this issue is completed before the other Sprint 1 issues (apart from issue#10 Game Logic), or doesn't matter that much? I'm thinking if I'm indeed only working on this project Fri/weekend, I should be assigned issues that fewer issues ''depend'' on?

**Comment by shrutirao94** [comment]
I've incorporated this in my code!

**Comment by arumoy-shome** [comment]
Closed in #13.
